language: rust
dist: xenial
cache: cargo
rust:
  - stable
os:
  - linux
env:
  global:
    - CARGO_MAKE_RUN_CODECOV="true"
addons:
  apt:
    packages:
      - libgsl0-dev
      - samtools
      - curl
script:
  - cargo install --debug cargo-make
  - cargo make ci-flow
